import type { Metadata } from 'next';
import { Vazirmatn } from 'next/font/google';
import './globals.css';
import Header from '@/components/header/Header';

const vazir = Vazirmatn({
  variable: '--font-vazir',
  subsets: ['arabic'],
  weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={` ${vazir.className} antialiased min-w-[360px] max-w-[1440px] w-full px-4 lg:px-28 min-h-svh mx-auto`}
      >
        <main className="mx-auto">
          <Header />
          {children}
          {/* footer */}
        </main>
      </body>
    </html>
  );
}
