import type { Metadata } from 'next';
import { Vazirmatn, Geist } from 'next/font/google';
import './globals.css';

const vazir = Vazirmatn({
  variable: '--font-vazir',
  subsets: ['arabic'],
  weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${vazir.variable} antialiased`}>{children}</body>
    </html>
  );
}
